INSERT INTO vw_custom_what_events (
  cartodb_id,
  the_geom,
  the_geom_webmercator,
  gz_id,
  user_id,
  local_datetime,
  local_month,
  local_day,
  local_month_text,
  latitude,
  longitude,
  poi_id,
  poi_name,
  rt_category_id,
  group_designation,
  tourism_region_name,
  state,
  what,
  category_id,
  display_full,
  parent_display_full
)
SELECT
  (cartodb_id + {maxid}) AS cartodb_id,
  the_geom,
  the_geom_webmercator,
  gz_id,
  user_id,
  local_datetime,
  local_month,
  local_day,
  local_month_text,
  latitude,
  longitude,
  poi_id,
  poi_name,
  rt_category_id,
  group_designation,
  tourism_region_name,
  state,
  what,
  category_id,
  display_full,
  parent_display_full
FROM {source}
WHERE 1=1
